name: php-otp-app
services:
  - name: php-otp-service
    runtime: php
    type: web
    routes:
      - name: php-otp-route
        path: /
    instance:
      size: micro
      regions:
        - fra  # Pilih region yang sesuai (misalnya fra untuk Frankfurt)
    env:
      MAILOSAUR_API_KEY: your_api_key       # API Key Mailosaur
      MAILOSAUR_SERVER_ID: your_server_id  # Server ID Mailosaur
    build:
      type: docker
      dockerfile: Dockerfile  # Gunakan Dockerfile untuk membangun aplikasi
    disk:
      persist: true  # Pastikan data disk persisten untuk aplikasi Anda
    ports:
      - "8080:80"  # Menentukan port yang akan digunakan
      
